### PR TITLE
Hossein alpha

### PR DESCRIPTION
**Pull request by Hosseinfatho**
Hello 
As my part
I added some AI that includes flocking Ghost whole the cube and they can pass through Walls
2- added Flicking Light near Golem as UI and when the player is near the Golem it starts to flick
3- Add a sound Alarm as UI when the Player Is in a Dangerous Zone

### CODE REVIEW

**Comment by Hosseinfatho** [comment]
Please check

**Review by peterPacho — DISMISSED** [review]
I'll trust you

**Comment by gradyl16** [comment]
## Design

The `MasterEnemy` GameObject (the golem thing) does not match the game theme -- neither does the ghost model you used (Casper-looking thing). We have discussed this multiple times -- we need to use models that adhere to the story / idea of the puzzle game.

## Functionality

### Needs Fix

The MasterEnemy does not move, it runs in place.

The ghosts are usually oriented laterally with the cube which looks really strange. Also, they don't seem to gravitate towards the player or take coherent paths.

### Looks Good

Lighting is a nice touch, along with proximity detection. Good job here.

Filling out the cube with more walls is also a nice addition.

**Review by Hosseinfatho — COMMENTED** [review]
good

**Review by Hosseinfatho — COMMENTED** [review]
Thanks

**Pull request merged**
