### PR TITLE
26 basic sound

### PR DESCRIPTION
**Pull request by gradyl16**
All testing/reviewing should be done on the scene named `Dylen_Alpha`.

Simple background music is added, playing on a loop and triggered on the Awake event. Also, upon "enemy" (i.e. patrol bot) death, a short sound is played to let the player know it has fallen. The choice for either of these sounds is subject to change, but they seem mildly appropriate/relevant to start with.

As a miscellaneous improvement, the scene's floorplan was extended to all sides of the cube. Each face features a ground-based enemy, just like the original left side (and top).

### CODE REVIEW

**Comment by Hosseinfatho** [comment]
Thanks

**Review by Hosseinfatho — APPROVED** [review]
Good

**Review by Hosseinfatho — APPROVED** [review]
Thanks

**Comment by peterPacho** [comment]
Null exceptions when enemy dies. Missing scene audio component?

**Comment by gradyl16** [comment]
> Null exceptions when enemy dies. Missing scene audio component?

Thanks for pointing this out. I probably forgot to save the scene -- why Unity scenes don't autosave, I will never know.

**Comment by gradyl16** [comment]
Closing without approvals to meet deadline. Note that fix was implemented for null refs & additional sound was added for transitioning from face to face on the cube.

**Review by Hosseinfatho — COMMENTED** [review]
good

**Pull request merged**
