### PR TITLE
UI work

### PR DESCRIPTION
**Pull request by peterPacho**
Some work on UI elements: main menu and pause menu.
Added prefab to quickly add pause menu to any new scene / level.

### CODE REVIEW

**Comment by Hosseinfatho** [comment]
good

**Review by Hosseinfatho — DISMISSED** [review]
good

**Comment by gradyl16** [comment]
Looks like there may be a bug.

Problem is essentially that menu items in the OptionsMenu are not clickable after opening the resolution dropdown menu. The bug does not reliably appear, and may be caused by opening drop down menu, clicking elsewhere on scene, then trying to interact with the menu again. Also, expected initial interaction with the options menu seems to prevent this from reoccurring.

A workaround is to just close and reopen the menu with <Esc> -- but this is obviously not ideal.

Overall, this bug is not a big deal. However, I'd prefer not to merge this into main until it is fixed. If it ends up being difficult to fix, we may change our priorities.

---

Everything else works fine according to my testing. Note that I did not test an actual build and thus could not verify the functionality of the resolution-based features.

**Comment by peterPacho** [comment]
> Looks like there may be a bug.
> 
> Problem is essentially that menu items in the OptionsMenu are not clickable after opening the resolution dropdown menu. The bug does not reliably appear, and may be caused by opening drop down menu, clicking elsewhere on scene, then trying to interact with the menu again. Also, expected initial interaction with the options menu seems to prevent this from reoccurring.
> 
> A workaround is to just close and reopen the menu with -- but this is obviously not ideal.
> 
> Overall, this bug is not a big deal. However, I'd prefer not to merge this into main until it is fixed. If it ends up being difficult to fix, we may change our priorities.
> 
> Everything else works fine according to my testing. Note that I did not test an actual build and thus could not verify the functionality of the resolution-based features.

Happens pretty much all the time when playing the game from editor. Can't replicate when playing from build. Please check on the build version.

**Review by Hosseinfatho — APPROVED** [review]
great thank you

**Review by gradyl16 — APPROVED** [review]

**Pull request merged**
